### PR TITLE
Detect if nix is installed

### LINKED ISSUE #27: `plan` and `install` should detect if nix is already installed
That would be nice to detect if nix was already installed when trying `install` or `plan`, I suppose there code is there because the uninstall process already do that.

Here are the results of install and plan after a successful installation

```
$ sudo ./harmonic install
Error: 
   0: Error executing action
   1: Placing channel configuration
   2: Creating file
   3: File exists `/root/.nix-channels`

Location:
   src/cli/subcommand/install.rs:77

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: harmonic::cli::subcommand::install::execute
      at src/cli/subcommand/install.rs:43
   1: harmonic::cli::execute
      at src/cli/mod.rs:29

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
and
```
$ sudo ./harmonic plan
Error: 
   0: Error executing action
   1: Placing channel configuration
   2: Creating file
   3: File exists `/root/.nix-channels`

Location:
   src/cli/subcommand/plan.rs:58

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: harmonic::cli::subcommand::plan::execute with channels=nixpkgs https://nixos.org/channels/nixpkgs-unstable daemon_user_count=32 no_modify_profile=false
      at src/cli/subcommand/plan.rs:24
   1: harmonic::cli::execute
      at src/cli/mod.rs:29

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### PR DESCRIPTION
**Pull request by Hoverbear**
Based off #50 since it introduces the error type we use

CLoses #27

### CODE REVIEW

**Comment by Hoverbear** [comment]
(CI is interacting with #52)

File: src/planner/linux/multi.rs [hunk 1]
```diff
@@ -30,6 +30,15 @@ impl Planner for LinuxMulti {
             return Err(Error::NixOs.into());
         }
 
+        // For now, we don't try to repair the user's Nix install or anything special.
+        if let Ok(_) = tokio::process::Command::new("nix")
```
Comment (cole-h) [inline src/planner/linux/multi.rs:34]: Does this work even if the `nix-command` feature is not enabled / is it guaranteed that we have `nix-command` enabled at this point?

If not, maybe it should become `if !(nix || nix-env)` (since `nix-env`, while it may some day go away, is what some places use to check for Nix, and even issues on the Nix repo request the output of `nix-env --version` to tell what version of Nix is being used).

Also, rather than just the bare command, it may be better to add `--version` or `--help` so that there there are no unintended side-effects (e.g. if some day `nix` by itself does something, rather than erroring as it does now).

**Review by cole-h — COMMENTED** [review]
Overall LGTM, just a small question. Once that gets addressed (even if it's just "don't care"), :shipit:

File: src/planner/linux/multi.rs (hunk 1 above)
Comment (Hoverbear) [reply src/planner/linux/multi.rs:34]: Ya, great catch. Thanks!

Comment (cole-h) [reply src/planner/linux/multi.rs:34]: I guess also `--extra-experimental-features nix-command` would also suffice in making this work without the need for `nix-env`.

Comment (Hoverbear) [reply src/planner/linux/multi.rs]: I like `nix-env` for this.

**Review by cole-h — APPROVED** [review]
