### PR TITLE
Planner error if on NixOS

### LINKED ISSUE #21: detect NixOS
That's unlikely anyone would try to use harmonic on NixOS like me, but the current result isn't good

```
> result/bin/harmonic -vv plan
  2022-10-26T12:33:46.914391Z TRACE harmonic::actions::meta::configure_shell_profile: Did not plan to edit `/etc/profile.d/nix.sh` as it does not exist.
    at src/actions/meta/configure_shell_profile.rs:32
    in harmonic::actions::meta::configure_shell_profile::plan
    in harmonic::actions::meta::configure_nix::plan
    in harmonic::cli::subcommand::plan::execute with channels: nixpkgs https://nixos.org/channels/nixpkgs-unstable, daemon_user_count: 32, no_modify_profile: false
    in harmonic::cli::execute

  2022-10-26T12:33:46.914521Z TRACE harmonic::actions::meta::configure_shell_profile: Did not plan to edit `/etc/zshrc` as it does not exist.
    at src/actions/meta/configure_shell_profile.rs:32
    in harmonic::actions::meta::configure_shell_profile::plan
    in harmonic::actions::meta::configure_nix::plan
    in harmonic::cli::subcommand::plan::execute with channels: nixpkgs https://nixos.org/channels/nixpkgs-unstable, daemon_user_count: 32, no_modify_profile: false
    in harmonic::cli::execute

  2022-10-26T12:33:46.914608Z TRACE harmonic::actions::meta::configure_shell_profile: Did not plan to edit `/etc/bash.bashrc` as it does not exist.
    at src/actions/meta/configure_shell_profile.rs:32
    in harmonic::actions::meta::configure_shell_profile::plan
    in harmonic::actions::meta::configure_nix::plan
    in harmonic::cli::subcommand::plan::execute with channels: nixpkgs https://nixos.org/channels/nixpkgs-unstable, daemon_user_count: 32, no_modify_profile: false
    in harmonic::cli::execute

  2022-10-26T12:33:46.914674Z TRACE harmonic::actions::meta::configure_shell_profile: Did not plan to edit `/etc/zsh/zshrc` as it does not exist.
    at src/actions/meta/configure_shell_profile.rs:32
    in harmonic::actions::meta::configure_shell_profile::plan
    in harmonic::actions::meta::configure_nix::plan
    in harmonic::cli::subcommand::plan::execute with channels: nixpkgs https://nixos.org/channels/nixpkgs-unstable, daemon_user_count: 32, no_modify_profile: false
    in harmonic::cli::execute

Error: 
   0: Error executing action
   1: Placing Nix configuration
   2: Creating file
   3: File exists `/etc/nix/nix.conf`

Location:
   src/cli/subcommand/plan.rs:58

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: harmonic::cli::subcommand::plan::execute with channels=nixpkgs https://nixos.org/channels/nixpkgs-unstable daemon_user_count=32 no_modify_profile=false
      at src/cli/subcommand/plan.rs:24
   1: harmonic::cli::execute
      at src/cli/mod.rs:29

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

### PR DESCRIPTION
**Pull request by Hoverbear**
Closes #21

### CODE REVIEW

File: src/planner/linux/multi.rs [hunk 1]
```diff
@@ -24,12 +24,29 @@ impl Planner for LinuxMulti {
     }
 
     async fn plan(self) -> Result<InstallPlan, Box<dyn std::error::Error + Sync + Send>> {
+        // If on NixOS, running `harmonic` is pointless
+        if Path::new("/etc/NIXOS").exists() {
```
Comment (cole-h) [inline src/planner/linux/multi.rs:28]: For posterity: this is a valid way to detect NixOS, because NixOS always sets up this file as part of setting up `/etc` itself: https://github.com/NixOS/nixpkgs/blob/bdd39e5757d858bd6ea58ed65b4a2e52c8ed11ca/nixos/modules/system/etc/setup-etc.pl#L145

**Review by cole-h — APPROVED** [review]
LGTM :tada:

File: src/planner/linux/multi.rs (hunk 1 above)
Comment (Hoverbear) [reply src/planner/linux/multi.rs:28]: I'll add this as a comment!
